{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7f158b7c-f5b8-425e-ba7a-2dce3ae29e86",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter host IP (default is 10.200.200.210):  10.200.200.210\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pinging 10.200.200.210 up to 40 times...\n",
      "\n",
      "Debug Output for Attempt 1:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 1: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 2:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 2: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 3:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 3: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 4:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 4: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 5:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 5: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 6:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 6: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 7:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 7: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 8:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 8: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 9:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time<1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 0ms, Maximum = 0ms, Average = 0ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 9: Success, Response Time: 0.50 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 10:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 10: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 11:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 11: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 12:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 12: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 13:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 13: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 14:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 14: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 15:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 15: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 16:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 16: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 17:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 17: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 18:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time<1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 0ms, Maximum = 0ms, Average = 0ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 18: Success, Response Time: 0.50 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 19:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 19: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 20:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 20: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 21:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 21: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 22:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 22: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 23:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 23: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 24:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 24: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 25:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 25: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 26:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 26: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 27:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 27: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 28:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 28: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 29:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 29: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 30:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 30: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 31:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 31: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 32:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 32: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 33:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 33: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 34:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 34: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 35:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 35: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 36:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 36: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 37:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 37: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 38:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 38: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 39:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 39: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n",
      "\n",
      "Debug Output for Attempt 40:\n",
      "\n",
      "Pinging 10.200.200.210 with 32 bytes of data:\n",
      "Reply from 10.200.200.210: bytes=32 time=1ms TTL=64\n",
      "\n",
      "Ping statistics for 10.200.200.210:\n",
      "    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\n",
      "Approximate round trip times in milli-seconds:\n",
      "    Minimum = 1ms, Maximum = 1ms, Average = 1ms\n",
      "\n",
      "Error getting signal strength: Command 'netsh wlan show interfaces' returned non-zero exit status 1.\n",
      "Attempt 40: Success, Response Time: 1.00 ms, Signal Strength: -100 dBm\n"
     ]
    },
    {
     "data": {
      "text/markdown": [
       "# Ping Report for Host: 10.200.200.210\n",
       "**Date:** 2025-05-13 08:37:45\n",
       "\n",
       "**Ping Test Results:**\n",
       "| Attempt | Timestamp          | Response Time (ms) | Status  | Signal Strength (dBm) |\n",
       "|---------|---------------------|---------------------|---------|-----------------------|\n",
       "|      1 | 2025-05-13 08:37:02 |            1.00 | Success  |                -100 |\n",
       "|      2 | 2025-05-13 08:37:03 |            1.00 | Success  |                -100 |\n",
       "|      3 | 2025-05-13 08:37:04 |            1.00 | Success  |                -100 |\n",
       "|      4 | 2025-05-13 08:37:05 |            1.00 | Success  |                -100 |\n",
       "|      5 | 2025-05-13 08:37:06 |            1.00 | Success  |                -100 |\n",
       "|      6 | 2025-05-13 08:37:07 |            1.00 | Success  |                -100 |\n",
       "|      7 | 2025-05-13 08:37:08 |            1.00 | Success  |                -100 |\n",
       "|      8 | 2025-05-13 08:37:09 |            1.00 | Success  |                -100 |\n",
       "|      9 | 2025-05-13 08:37:10 |            0.50 | Success  |                -100 |\n",
       "|     10 | 2025-05-13 08:37:11 |            1.00 | Success  |                -100 |\n",
       "|     11 | 2025-05-13 08:37:12 |            1.00 | Success  |                -100 |\n",
       "|     12 | 2025-05-13 08:37:13 |            1.00 | Success  |                -100 |\n",
       "|     13 | 2025-05-13 08:37:15 |            1.00 | Success  |                -100 |\n",
       "|     14 | 2025-05-13 08:37:16 |            1.00 | Success  |                -100 |\n",
       "|     15 | 2025-05-13 08:37:17 |            1.00 | Success  |                -100 |\n",
       "|     16 | 2025-05-13 08:37:18 |            1.00 | Success  |                -100 |\n",
       "|     17 | 2025-05-13 08:37:19 |            1.00 | Success  |                -100 |\n",
       "|     18 | 2025-05-13 08:37:20 |            0.50 | Success  |                -100 |\n",
       "|     19 | 2025-05-13 08:37:21 |            1.00 | Success  |                -100 |\n",
       "|     20 | 2025-05-13 08:37:22 |            1.00 | Success  |                -100 |\n",
       "|     21 | 2025-05-13 08:37:23 |            1.00 | Success  |                -100 |\n",
       "|     22 | 2025-05-13 08:37:24 |            1.00 | Success  |                -100 |\n",
       "|     23 | 2025-05-13 08:37:25 |            1.00 | Success  |                -100 |\n",
       "|     24 | 2025-05-13 08:37:26 |            1.00 | Success  |                -100 |\n",
       "|     25 | 2025-05-13 08:37:27 |            1.00 | Success  |                -100 |\n",
       "|     26 | 2025-05-13 08:37:28 |            1.00 | Success  |                -100 |\n",
       "|     27 | 2025-05-13 08:37:30 |            1.00 | Success  |                -100 |\n",
       "|     28 | 2025-05-13 08:37:31 |            1.00 | Success  |                -100 |\n",
       "|     29 | 2025-05-13 08:37:32 |            1.00 | Success  |                -100 |\n",
       "|     30 | 2025-05-13 08:37:33 |            1.00 | Success  |                -100 |\n",
       "|     31 | 2025-05-13 08:37:34 |            1.00 | Success  |                -100 |\n",
       "|     32 | 2025-05-13 08:37:35 |            1.00 | Success  |                -100 |\n",
       "|     33 | 2025-05-13 08:37:36 |            1.00 | Success  |                -100 |\n",
       "|     34 | 2025-05-13 08:37:37 |            1.00 | Success  |                -100 |\n",
       "|     35 | 2025-05-13 08:37:38 |            1.00 | Success  |                -100 |\n",
       "|     36 | 2025-05-13 08:37:39 |            1.00 | Success  |                -100 |\n",
       "|     37 | 2025-05-13 08:37:40 |            1.00 | Success  |                -100 |\n",
       "|     38 | 2025-05-13 08:37:42 |            1.00 | Success  |                -100 |\n",
       "|     39 | 2025-05-13 08:37:43 |            1.00 | Success  |                -100 |\n",
       "|     40 | 2025-05-13 08:37:44 |            1.00 | Success  |                -100 |\n",
       "\n",
       "**Summary:**\n",
       "- Total Attempts: 40\n",
       "- Successful Pings: 40\n",
       "- Failed Pings: 0\n",
       "- Average Response Time: 0.97 ms\n",
       "- Average Signal Strength: -100.00 dBm\n"
      ],
      "text/plain": [
       "<IPython.core.display.Markdown object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Text report generated: ping_report.txt\n"
     ]
    }
   ],
   "source": [
    "import subprocess\n",
    "import time\n",
    "import sys\n",
    "\n",
    "def get_signal_strength():\n",
    "    \"\"\"Measure Wi-Fi signal strength using netsh and return percentage (or None if unavailable).\"\"\"\n",
    "    try:\n",
    "        result = subprocess.check_output(\"netsh wlan show interfaces\", shell=True, text=True)\n",
    "        print(f\"\\nDebug netsh Output:\\n{result}\")  # Debug: Print raw netsh output\n",
    "        for line in result.splitlines():\n",
    "            if \"Signal\" in line:\n",
    "                percentage = int(line.split(\":\")[1].strip().replace(\"%\", \"\"))\n",
    "                return percentage\n",
    "        return None\n",
    "    except Exception as e:\n",
    "        print(f\"Error getting signal strength: {e}\")\n",
    "        return None\n",
    "\n",
    "def percentage_to_dbm(percentage):\n",
    "    \"\"\"Convert signal strength percentage to approximate dBm.\"\"\"\n",
    "    if percentage is None or percentage == 0:\n",
    "        return -100  # Assume -100 dBm if no signal\n",
    "    # Rough approximation: 100% ≈ -30 dBm, 0% ≈ -100 dBm (linear mapping)\n",
    "    dbm = -100 + (percentage * 0.7)  # Maps 0% to -100 dBm, 100% to -30 dBm\n",
    "    return round(dbm)\n",
    "\n",
    "def ping_host(host, attempts=40):\n",
    "    results = []\n",
    "    print(f\"Pinging {host} up to {attempts} times...\")\n",
    "    \n",
    "    for i in range(attempts):\n",
    "        # Run ping command and capture output\n",
    "        ping_process = subprocess.run(['ping', '-n', '1', '-w', '2000', host], \n",
    "                                     stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)\n",
    "        timestamp = time.strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "        \n",
    "        # Debug: Print raw output to see what's being captured\n",
    "        print(f\"\\nDebug Output for Attempt {i+1}:\\n{ping_process.stdout}\")\n",
    "        if ping_process.stderr:\n",
    "            print(f\"Error Output: {ping_process.stderr}\")\n",
    "\n",
    "        # Check if ping was successful\n",
    "        if \"Reply from\" in ping_process.stdout:\n",
    "            # Extract response time\n",
    "            for line in ping_process.stdout.splitlines():\n",
    "                if \"time=\" in line or \"time<\" in line:  # Handle both \"time=1ms\" and \"time<1ms\"\n",
    "                    try:\n",
    "                        if \"time<\" in line:\n",
    "                            response_time = 0.5  # Approximate for \"time<1ms\"\n",
    "                        else:\n",
    "                            response_time = float(line.split(\"time=\")[1].split(\"ms\")[0])\n",
    "                        status = \"Success\"\n",
    "                        break\n",
    "                    except (IndexError, ValueError):\n",
    "                        response_time = 0\n",
    "                        status = \"Failed\"\n",
    "                        break\n",
    "            else:\n",
    "                response_time = 0\n",
    "                status = \"Failed\"\n",
    "        else:\n",
    "            response_time = 0\n",
    "            status = \"Failed\"\n",
    "        \n",
    "        # Measure signal strength for this attempt\n",
    "        signal_percentage = get_signal_strength()\n",
    "        signal_dbm = percentage_to_dbm(signal_percentage)\n",
    "        \n",
    "        results.append((timestamp, response_time, status, signal_dbm))\n",
    "        print(f\"Attempt {i+1}: {status}, Response Time: {response_time:.2f} ms, Signal Strength: {signal_dbm} dBm\" \n",
    "              if status == \"Success\" else f\"Attempt {i+1}: {status}, Signal Strength: {signal_dbm} dBm\")\n",
    "        \n",
    "        time.sleep(1)  # Delay between pings\n",
    "\n",
    "    return results\n",
    "\n",
    "def generate_text_report(results, host):\n",
    "    # Generate report content as plain text for command-line output\n",
    "    report = f\"Ping Report for Host: {host}\\n\"\n",
    "    report += f\"Date: {time.strftime('%Y-%m-%d %H:%M:%S')}\\n\\n\"\n",
    "    report += \"Ping Test Results:\\n\"\n",
    "    report += \"Attempt | Timestamp          | Response Time (ms) | Status  | Signal Strength (dBm)\\n\"\n",
    "    report += \"-\" * 80 + \"\\n\"\n",
    "    \n",
    "    successful_pings = sum(1 for _, _, status, _ in results if status == \"Success\")\n",
    "    total_response_time = sum(r[1] for r in results if r[1] > 0)\n",
    "    avg_response_time = total_response_time / successful_pings if successful_pings > 0 else 0\n",
    "    failed_pings = len(results) - successful_pings\n",
    "    avg_signal_dbm = sum(r[3] for r in results) / len(results) if results else -100\n",
    "\n",
    "    for i, (timestamp, response_time, status, signal_dbm) in enumerate(results, 1):\n",
    "        report += f\"{i:<7} | {timestamp} | {response_time:<18.2f} | {status:<7} | {signal_dbm:<19}\\n\"\n",
    "    \n",
    "    report += \"\\nSummary:\\n\"\n",
    "    report += f\"Total Attempts: {len(results)}\\n\"\n",
    "    report += f\"Successful Pings: {successful_pings}\\n\"\n",
    "    report += f\"Failed Pings: {failed_pings}\\n\"\n",
    "    report += f\"Average Response Time: {avg_response_time:.2f} ms\\n\"\n",
    "    report += f\"Average Signal Strength: {avg_signal_dbm:.2f} dBm\\n\"\n",
    "\n",
    "    # Save to file\n",
    "    with open(\"ping_report.txt\", \"w\") as f:\n",
    "        f.write(report)\n",
    "    \n",
    "    # Print report to console\n",
    "    print(report)\n",
    "    print(\"Text report generated: ping_report.txt\")\n",
    "\n",
    "# Host selection for command-line usage\n",
    "default_host = \"10.200.200.210\"\n",
    "host = default_host\n",
    "\n",
    "# Check for command-line arguments\n",
    "if len(sys.argv) > 1:\n",
    "    host = sys.argv[1]\n",
    "\n",
    "# Run the ping and generate report\n",
    "results = ping_host(host)\n",
    "generate_text_report(results, host)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bb8a561-12ed-45a7-ac3f-5818e763374c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c162ecd-e4b5-490a-9301-376fb69ceb7e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "LLM Environment",
   "language": "python",
   "name": "llm_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
